### ISSUE TITLE
Comparison/join efforts with requests_mock

### ISSUE THREAD

**Issue by corehack** [getsentry/responses#182]
There's a similar library in openstack which has similar features and purpose https://github.com/openstack/requests-mock
I wasn't able to find any comparison between the two, and its possible the projects duplicate each other's efforts. Would be nice to have a guide to make a decision between them, if there are any significant differences etc

**Comment by dcramer** [comment]
I assume its a classic case of Not Invented Here. Not going to put any effort into comparing other open source utilities. I'd say use whatever works for you, but you can often judge a project by the number of users (stars/pypi), and the age of contributions. Responses is maintained (we use it heavily), and looks to cover a lot of the same stuff as the other project. I'm sure there are things that are different though. I would agree however that the world would be much better off if there was a single solution that did things well, rather than N choices that did things somewhat well.

**Comment by corehack** [comment]
Example I found.
requests_mock has request headers matching feature, while responses does not
There's only 1 year old pull request https://github.com/getsentry/responses/pull/114

**Comment by a-pertsev** [comment]
> Example I found.
requests_mock has request headers matching feature, while responses does not
There's only 1 year old pull request #114

Yeah, i was confused a bit about lack of attention this PR got.
Maybe my decision about mocking library i should use was incorrect =(

**Comment by corehack** [comment]
It looks like there's not much attention to PRs at all. Well, it's perfectly fine if maintainers don't want any new features (IMHO request headers matching is a must-have).

**Comment by dcramer** [comment]
We could look at supporting it, but to be honest it's pretty easy to build a complex request mock now that the whole thing is based on a response class mechanism. At the end of the day there's just far too many 'types' of matches you'd want to support to have simple flags for them all. That said, I do think it would be useful to support headers, or at the very least support something common like authorization.

(There is plenty of attention to pull requests on this repo, but we dont merge features 'just because' as it means we have to continue answering tickets/supporting those features, and the quality of them often leads to other complexity)

**Comment by a-pertsev** [comment]
@dcramer well, it's a good point about complexity, but why just not to close all this awaiting PRs if they are not going to be merged?

**Comment by dcramer** [comment]
Honestly? Because I have like 1000 more important things to do. 

We maintain the project and at times will clean up old issues and PRs but doing that across hundreds of repos is expensive when the only benefit is for others (and we generally aren’t building tools for others, but rather for ourselves). 

Not saying we can’t pull in header matching, and the PR was probably lost in the 500 daily emails I get, but anytime someone suggests we’re bad at maintaining things it triggers decades of maintainer rage.

Generally we’ve merged changes that are well tested and don’t break functionality, but I’ve definitely had to spend ample personal time fixing patches that provide no personal value or even utility at Sentry.
