### ISSUE TITLE
Passthroughs should override registered matches

### ISSUE THREAD

**Issue by tinvaan** [getsentry/responses#388]
Overriding passthru essentially enables a user to add an exception to a generic rule (such as when using regexps). This especially useful when using callbacks. Consider the below example, for instance

```python
def callback_method(request):
    if request.path_url == "/allow/this/route":
        responses.add_passthru(request.url)
        r = requests.get(request.url)
        return (r.status_code, dict(r.headers), r.content)
    return (200, {"Content-Type": "application/json", json.dumps({"data": "mocked data"})})

responses.add_callback(
    responses.GET,
    re.compile("https://example.com"),
    callback=callback_method,
    content_type="application/json"
)

requests.get("https://example.com/mocked/route")   # Should return a mocked response
requests.get("https://example.com/allow/this/route") # Should return an actual response
```
Any thoughts? I have a fix tested and ready and would like to push it upstream.

**Comment by carloshorn** [comment]
@tinvaan, I think #400 introduced a feature that may enable you to deal with your usecase.
Instead of adding new passthroughs in a callback during the test, you may just register a `PassthroughResponse`, for the specific requests at the beginning of the test. 
In my opinion, this approach would be cleaner, because you would not modify the state of your `RequestsMock` instance during the execution of your test, but instead simply provide responses for any expected requests before running your actual test lines.
