### ISSUE TITLE
A stream request blocks on response.iter_content when chunk_size=None

### ISSUE THREAD

**Issue by NorbertWasilewski** [getsentry/responses#438]
A response is blocking on stream request while iterating over content with chunk_size=None

### Environment

responses==0.15.0 requests==2.26.0   on python 3.7.8, but I believe other python versions are affected as well.
The problem is new in version 0.15.0 and affects 0.16.0 too.

### Steps to Reproduce
Install requests and responses:
```
pip install responses==0.15.0 requests==2.26.0 
```
Run below code
```python
import responses
import requests

with responses.RequestsMock() as fakes:
    fakes.add(responses.GET, 'https://example.com', status=200,
            content_type='application/octet-stream',
            body=b'This is test',
            auto_calculate_content_length=True
            )
    res = requests.get('https://example.com', stream=True)
    for chunk in res.iter_content(chunk_size=None):
        print(chunk)
```

### Expected Result

A code prints out `b'This is test'` and returns. 

### Actual Result

A code prints out `b'This is test'` and blocks waiting for more data. As far as I could debug it's blocking on  [this loop of urllib3](https://github.com/urllib3/urllib3/blob/1.26.7/src/urllib3/response.py#L575-L579), which suggests that `responses` doesn't close a stream once it's fully read.

**Comment by beliaev-maksim** [comment]
@NorbertWasilewski 
we recently made some fixes on `stream`

version 0.16 is already scheduled and will be published soon
in meantime, can you please test on latest master?

**Comment by beliaev-maksim** [comment]
The problem is actually quite deep.
Right now `Response` objects uses `StringIO` to mock request body. Since object must be like a file.
but at the same time you call with `None`, and since we go by different path in `urllib3`, we face non-closed object. `urllib3` does not close object when called with `None` (see screenshot below)
I will perform further investigation to see if we can find workaround
![image](https://user-images.githubusercontent.com/51964909/142216675-7e1f7faf-c5f0-4721-b742-ced0b9183aff.png)
